### ISSUE TITLE
ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by stevobujica** [iotaeco/iota-database-tutorial#1]
Hello,
I'm trying to install this on Centos V7. when I run `npm install` I get the error bellow:
`ffi_bindings.target.mk:104: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/iota-database-tutorial-master/node_modules/ffi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-127-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/iota-database-tutorial-master/node_modules/ffi
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN iota-database-tutorial@1.0.4 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-13T14_31_32_639Z-debug.log
root@vmi187578:/home/iota-database-tutorial-master# n latestgyp ERR! node -v v10.4.1

  Error: invalid version latestgyp

`
Any guide?

**Comment by obany** [comment]
To perform the proof of work we use ccurl.lib.js. This is a native c library that is accessed using the node ffi module.
Node ffi as part of its install has to build an interop library that is native to the platform you are running on.
This looks like the step that is failing, I would suggest looking at the npm package for ffi to see if they have any suggestions for your specific platform.
